// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhk-lxz35DpLt07UCJLUkIfwo7cCD7EQc',
    appId: '1:173957862218:web:dba26082f1b2ba54df67b3',
    messagingSenderId: '173957862218',
    projectId: 'student-analytics-263',
    authDomain: 'student-analytics-263.firebaseapp.com',
    storageBucket: 'student-analytics-263.appspot.com',
    measurementId: 'G-BM8E5WX1FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6UJEJq7GUbXpXQpz2YDckcoYqauZkhlk',
    appId: '1:173957862218:android:db1634ede07cf524df67b3',
    messagingSenderId: '173957862218',
    projectId: 'student-analytics-263',
    storageBucket: 'student-analytics-263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXVsUxG1XRJxrbB7dhYolBbmA1_XwWgmI',
    appId: '1:173957862218:ios:09cd43fd4c34fc28df67b3',
    messagingSenderId: '173957862218',
    projectId: 'student-analytics-263',
    storageBucket: 'student-analytics-263.appspot.com',
    iosBundleId: 'com.example.studentAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXVsUxG1XRJxrbB7dhYolBbmA1_XwWgmI',
    appId: '1:173957862218:ios:ed95e484b0e24a96df67b3',
    messagingSenderId: '173957862218',
    projectId: 'student-analytics-263',
    storageBucket: 'student-analytics-263.appspot.com',
    iosBundleId: 'com.example.studentAnalytics.RunnerTests',
  );
}
