// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIVd-GMeOyH0MdNDQxvl80rVMj7EjGiEE',
    appId: '1:29145780125:web:bfb8383a3a1cc5c00a2974',
    messagingSenderId: '29145780125',
    projectId: 'student-analytics-24',
    authDomain: 'student-analytics-24.firebaseapp.com',
    storageBucket: 'student-analytics-24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGMJEZWye2hR97n4fpJkva-S6lXhBBq5g',
    appId: '1:29145780125:android:0da425a3bcd39a550a2974',
    messagingSenderId: '29145780125',
    projectId: 'student-analytics-24',
    storageBucket: 'student-analytics-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWKjg9lmMRd6OMOMMjd_Ev5Oodubp1sDc',
    appId: '1:29145780125:ios:47c9f8e7770b77920a2974',
    messagingSenderId: '29145780125',
    projectId: 'student-analytics-24',
    storageBucket: 'student-analytics-24.appspot.com',
    iosBundleId: 'com.example.studentAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWKjg9lmMRd6OMOMMjd_Ev5Oodubp1sDc',
    appId: '1:29145780125:ios:8dbb0ba71d40a6250a2974',
    messagingSenderId: '29145780125',
    projectId: 'student-analytics-24',
    storageBucket: 'student-analytics-24.appspot.com',
    iosBundleId: 'com.example.studentAnalytics.RunnerTests',
  );
}
